"""Typed configuration package (YAML + environment overrides)."""

from config.settings import (
    ENV_OVERRIDES,
    PROJECT_ROOT,
    AnalyticsConfig,
    FormConfig,
    HudConfig,
    MovementConfig,
    OutputConfig,
    PersonSelectionConfig,
    PoseModelConfig,
    PostureConfig,
    PushUpConfig,
    RuntimeConfig,
    Settings,
    SkeletonConfig,
    SmoothingConfig,
    ValidationConfig,
    VideoConfig,
    VisualizationConfig,
    describe_dataclass,
    hex_to_bgr,
    load_settings,
    set_nested,
    settings_to_dict,
)

__all__ = [
    "ENV_OVERRIDES",
    "PROJECT_ROOT",
    "AnalyticsConfig",
    "FormConfig",
    "HudConfig",
    "MovementConfig",
    "OutputConfig",
    "PersonSelectionConfig",
    "PoseModelConfig",
    "PostureConfig",
    "PushUpConfig",
    "RuntimeConfig",
    "Settings",
    "SkeletonConfig",
    "SmoothingConfig",
    "ValidationConfig",
    "VideoConfig",
    "VisualizationConfig",
    "describe_dataclass",
    "hex_to_bgr",
    "load_settings",
    "set_nested",
    "settings_to_dict",
]
