"""Workout report generation (JSON / CSV / Markdown)."""

from __future__ import annotations

import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from src.analytics.session_tracker import SessionSummary, SessionTracker
from src.utils.helpers import ensure_dir, format_duration, timestamp_slug
from src.utils.logger import get_logger

logger = get_logger(__name__)

SPARK_CHARS = "▁▂▃▄▅▆▇█"


@dataclass(slots=True)
class ReportPaths:
    """Files produced by :func:`generate_reports`."""

    json_path: Optional[Path] = None
    csv_path: Optional[Path] = None
    markdown_path: Optional[Path] = None

    def existing(self) -> List[Path]:
        """Only the reports that were actually written."""
        return [path for path in (self.json_path, self.csv_path, self.markdown_path) if path is not None]


def sparkline(values: List[float], width: int = 60) -> str:
    """Render a compact text sparkline for the Markdown report."""
    finite = [value for value in values if math.isfinite(value)]
    if not finite:
        return ""
    if len(finite) > width:
        step = len(finite) / width
        finite = [finite[int(index * step)] for index in range(width)]
    low, high = min(finite), max(finite)
    if high - low < 1e-6:
        return SPARK_CHARS[4] * len(finite)
    return "".join(SPARK_CHARS[min(len(SPARK_CHARS) - 1, int((value - low) / (high - low) * (len(SPARK_CHARS) - 1)))] for value in finite)


def horizontal_bar(label: str, value: float, maximum: float, width: int = 24) -> str:
    """Render an ASCII bar for the state-duration section."""
    ratio = 0.0 if maximum <= 0 else max(0.0, min(1.0, value / maximum))
    filled = int(round(ratio * width))
    return f"{label:<10} {'█' * filled}{'·' * (width - filled)} {value:5.1f}s"


def render_markdown(
    tracker: SessionTracker,
    summary: Optional[SessionSummary] = None,
    *,
    title: str = "AI-Powered Push-Up Counter",
    source_name: str = "",
    pose_backend: str = "",
) -> str:
    """Render the human-readable Markdown workout report."""
    summary = summary or tracker.summary()
    frame_scores = [frame.form_score for frame in tracker.frames if math.isfinite(frame.form_score)]
    rep_lines: List[str] = []
    for rep in tracker.reps:
        status = "✅ valid" if rep.valid else f"❌ {rep.reason}"
        depth = f"{rep.min_elbow_angle:.0f}°" if math.isfinite(rep.min_elbow_angle) else "--"
        score = f"{rep.form_score:.0f}" if math.isfinite(rep.form_score) else "--"
        rep_lines.append(f"| {rep.index} | {format_duration(rep.timestamp)} | {rep.duration_s:.2f}s | {depth} | {score} | {status} |")

    state_max = max(summary.time_up, summary.time_down, summary.time_moving, 1e-6)
    invalid_reasons: Dict[str, int] = {}
    for rep in tracker.reps:
        if not rep.valid:
            invalid_reasons[rep.reason] = invalid_reasons.get(rep.reason, 0) + 1

    lines: List[str] = [
        f"# {title} - Workout Report",
        "",
        f"- **Generated:** {timestamp_slug(fmt='%Y-%m-%d %H:%M:%S')}",
        f"- **Source:** {source_name or 'n/a'}",
        f"- **Pose backend:** {pose_backend or 'n/a'}",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "| --- | --- |",
    ]
    for label, value in summary.headline_rows():
        lines.append(f"| {label} | {value} |")

    lines += [
        "",
        "## Time in each phase",
        "",
        "```",
        horizontal_bar("UP", summary.time_up, state_max),
        horizontal_bar("MOVING", summary.time_moving, state_max),
        horizontal_bar("DOWN", summary.time_down, state_max),
        "```",
        "",
        "## Form score over time",
        "",
        f"```{sparkline(frame_scores)}```" if frame_scores else "```no data```",
        "",
        "## Repetition log",
        "",
    ]
    if rep_lines:
        lines += ["| # | Time | Duration | Depth | Form | Verdict |", "| --- | --- | --- | --- | --- | --- |", *rep_lines]
    else:
        lines.append("_No repetitions recorded._")

    if invalid_reasons:
        lines += ["", "## Invalid repetitions", ""]
        for reason, count in sorted(invalid_reasons.items(), key=lambda item: -item[1]):
            lines.append(f"- {reason}: {count}")

    lines += [
        "",
        "---",
        "",
        "_Generated by the AI-Powered Push-Up Counter (RF-DETR pose + joint-angle state machine)._",
        "",
    ]
    return "\n".join(lines)


def generate_reports(
    tracker: SessionTracker,
    reports_dir: str | Path,
    *,
    formats: Tuple[str, ...] = ("json", "csv", "md"),
    prefix: str = "workout_report",
    source_name: str = "",
    pose_backend: str = "",
) -> ReportPaths:
    """Write the selected report formats into ``reports_dir``.

    Args:
        tracker: The session to export.
        reports_dir: Destination directory (created when missing).
        formats: Subset of ``("json", "csv", "md")``.
        prefix: Filename prefix.
        source_name: Name of the video/webcam source (shown in the report).
        pose_backend: Backend description (shown in the report).

    Returns:
        A :class:`ReportPaths` with the files that were written.
    """
    directory = ensure_dir(reports_dir)
    stamp = timestamp_slug()
    summary = tracker.summary()
    paths = ReportPaths()

    if "json" in formats:
        payload = {
            "generated_at": stamp,
            "source": source_name,
            "pose_backend": pose_backend,
            **tracker.to_dict(),
        }
        paths.json_path = directory / f"{prefix}_{stamp}.json"
        paths.json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    if "csv" in formats:
        frame_df = tracker.to_dataframe()
        rep_df = tracker.reps_dataframe()
        paths.csv_path = directory / f"{prefix}_{stamp}_frames.csv"
        frame_df.to_csv(paths.csv_path, index=False)
        if not rep_df.empty:
            rep_path = directory / f"{prefix}_{stamp}_reps.csv"
            rep_df.to_csv(rep_path, index=False)
            logger.info("Rep CSV written: %s", rep_path.name)

    if "md" in formats:
        markdown = render_markdown(tracker, summary, source_name=source_name, pose_backend=pose_backend)
        paths.markdown_path = directory / f"{prefix}_{stamp}.md"
        paths.markdown_path.write_text(markdown, encoding="utf-8")

    for path in paths.existing():
        logger.info("Report written: %s", path.name)
    return paths


__all__ = ["ReportPaths", "generate_reports", "render_markdown", "sparkline", "horizontal_bar"]
